### PR TITLE
add beverages

### PR DESCRIPTION
**Pull request by teenteennnii**

### CODE REVIEW

**Review by ishiasaka — CHANGES_REQUESTED** [review]
Please remove `.idea` folder or ignored it

**Review by Supakrit65 — CHANGES_REQUESTED** [review]
.idea founded

**Comment by VorakornLeechavanan** [comment]
> Please remove `.idea` folder or ignored it

ok

**Comment by teenteennnii** [comment]
please hyperlink link your github id

**Comment by VorakornLeechavanan** [comment]
> Please remove `.idea` folder or ignored it

already delete rub

**Comment by VorakornLeechavanan** [comment]
> please hyperlink link your github id

okay

**Pull request closed without merging**
